### ISSUE TITLE
随机xjj插件里的api貌似有点宏病毒

### ISSUE THREAD

**Issue by MiaoR1Zibing** [xiaotian2333/yunzai-plugins-Single-file#1]
![image](https://github.com/user-attachments/assets/24f93ed6-f9f6-43fa-8438-3dd7093d67bd)
（不知道）

**Comment by xiaotian2333** [comment]
> ![image](https://github.com/user-attachments/assets/24f93ed6-f9f6-43fa-8438-3dd7093d67bd)
> （不知道）

看报毒的意思是个下载东西类型的病毒，可能是这个api被火绒风控了，我尝试向火绒提交样本看看能不能消除报毒

**Comment by xiaotian2333** [comment]
看看还有没有报毒，提交样本这么多天了，火绒也没回我
